### ISSUE TITLE
No implementation found for long org.opencv.core.Mat.n_Mat()

### ISSUE THREAD

**Issue by HaraldWolz** [zynkware/Document-Scanning-Android-SDK#8]
Getting the following exception when starting the activity.
Fresh project Android 13
compile/targetSdk 32
gradle 7.2.1

 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: myapplication, PID: 15560
    java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.core.Mat.n_Mat() (tried Java_org_opencv_core_Mat_n_1Mat and Java_org_opencv_core_Mat_n_1Mat__)
        at org.opencv.core.Mat.n_Mat(Native Method)
        at org.opencv.core.Mat.<init>(Mat.java:23)
        at com.zynksoftware.documentscanner.common.extensions.ImageProxyExtensionsKt.yuvToRgba(ImageProxyExtensions.kt:29)
        at com.zynksoftware.documentscanner.ui.components.scansurface.ScanSurfaceView$setUseCases$2.analyze(ScanSurfaceView.kt:162)
        at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$1$androidx-camera-core-ImageAnalysis(ImageAnalysis.java:367)
        at androidx.camera.core.ImageAnalysis$$ExternalSyntheticLambda0.analyze(Unknown Source:4)
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer.lambda$analyzeImage$0$androidx-camera-core-ImageAnalysisAbstractAnalyzer(ImageAnalysisAbstractAnalyzer.java:121)
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer$$ExternalSyntheticLambda1.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by iulian-buzila** [comment]
have you added init method in your Base application class?
